// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'env/env.dart';

const String kFirebaseKey = Env.firebaseKey;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: kFirebaseKey,
    appId: '1:540322739075:web:c91305b02e97bedd6ebcb6',
    messagingSenderId: '540322739075',
    projectId: 'fluttersocial-9a2ae',
    authDomain: 'fluttersocial-9a2ae.firebaseapp.com',
    storageBucket: 'fluttersocial-9a2ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: kFirebaseKey,
    appId: '1:540322739075:android:d3580e80284566786ebcb6',
    messagingSenderId: '540322739075',
    projectId: 'fluttersocial-9a2ae',
    storageBucket: 'fluttersocial-9a2ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: kFirebaseKey,
    appId: '1:540322739075:ios:0e499b394500c5656ebcb6',
    messagingSenderId: '540322739075',
    projectId: 'fluttersocial-9a2ae',
    storageBucket: 'fluttersocial-9a2ae.appspot.com',
    iosClientId:
        '540322739075-02ngq0kfu4g7ub2amumj31s1498s48qi.apps.googleusercontent.com',
    iosBundleId: 'com.massimilianoporzio.flutterSocialFirebase',
  );
}
