// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_social_firebase/test/src/features/auth/presentation/pages/sign_in_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:flutter_social_firebase/src/features/auth/presentation/blocs/sign_in/sign_in_cubit.dart'
    as _i2;
import 'package:flutter_social_firebase/src/logs/bloc_logger.dart' as _i5;
import 'package:loggy/loggy.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignInState_0 extends _i1.SmartFake implements _i2.SignInState {
  _FakeSignInState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoggy_1<T extends _i3.LoggyType> extends _i1.SmartFake
    implements _i3.Loggy<T> {
  _FakeLoggy_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInCubit extends _i1.Mock implements _i2.SignInCubit {
  MockSignInCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SignInState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSignInState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.SignInState);
  @override
  _i4.Stream<_i2.SignInState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.SignInState>.empty(),
      ) as _i4.Stream<_i2.SignInState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i3.Loggy<_i5.BlocLoggy> get loggy => (super.noSuchMethod(
        Invocation.getter(#loggy),
        returnValue: _FakeLoggy_1<_i5.BlocLoggy>(
          this,
          Invocation.getter(#loggy),
        ),
      ) as _i3.Loggy<_i5.BlocLoggy>);
  @override
  void emailChanged(String? value) => super.noSuchMethod(
        Invocation.method(
          #emailChanged,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void passwordChanged(String? value) => super.noSuchMethod(
        Invocation.method(
          #passwordChanged,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> resetEmailInput() => (super.noSuchMethod(
        Invocation.method(
          #resetEmailInput,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> resetPasswordInput() => (super.noSuchMethod(
        Invocation.method(
          #resetPasswordInput,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void emit(_i2.SignInState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i6.Change<_i2.SignInState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
